### PR TITLE
Merge Named Pipes and TCP Pivots to GRPC branch

### PR DESCRIPTION
**Pull request by h4ng3r**
This PR merges the pivot branch with GRPC branch. The changes introduces are:

1. Added C2 pivoting transports for Named Pipes and TCP (named pivottcp to avoid confusions)

2. Refactored to move code away from handlers and avoid duping code.

3. Now the Pivot is not automatically sending the MsgPivotOpen. This will be sent when detecting MsgRegister. The Pivot will MsgPivotOpen + MsgRegister, so the server now creates the session with the information from MsgPivotOpen.

4. Fixed a bug that prevented pivoting slivers to reconnect if the server was rebooted. For the I changed the following:

   - Pivot handlers have to be always on, added StartPivotListener() on all C2 StartXXXXXXX functions.

    - Added "pivots.ReconnectActivePivots(connection)" on sliver mainLoop, this function will resend PivotOpen for active pivots if a new connection is stablished.

    - The connection now is always pulled from the Sliver using "tansport.GetActiveConnection()"

### CODE REVIEW

**Comment by rkervella** [comment]
Doesn't seem to compile here:
```
~/code/golang/src/github.com/bishopfox/sliver make linux                                                                                                                                                                                                                     sliver (h4ng3r-grpc_smb)
packr clean
rm -f ./protobuf/client/*.pb.go
rm -f ./protobuf/sliver/*.pb.go
rm -f ./client/version/version.go
rm -f sliver-client sliver-server *.exe
protoc -I protobuf/ protobuf/commonpb/common.proto --go_out=paths=source_relative:protobuf/
protoc -I protobuf/ protobuf/sliverpb/sliver.proto --go_out=paths=source_relative:protobuf/
protoc -I protobuf/ protobuf/clientpb/client.proto --go_out=paths=source_relative:protobuf/
clientpb/client.proto:240:5: "TCP" is already defined in "clientpb".
clientpb/client.proto:240:5: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "TCP" must be unique within "clientpb", not just within "StageProtocol".
make: *** [Makefile:82: pb] Error 1
```

**Comment by moloch--** [comment]
@h4ng3r Looking really good so far, but I do have one small request: the `commonpb.Response` now contains the `Err` field, could you use that for`Err` in response objects e.g. https://github.com/BishopFox/sliver/pull/182/files#diff-19ce4a8cea689075fb9c355949f32dd2R196

**Comment by h4ng3r** [comment]
@moloch--, sure I'll update the PR today.

**Comment by h4ng3r** [comment]
@moloch-- fixed. nice catch.

**Comment by moloch--** [comment]
@h4ng3r great work!

**Pull request merged**
