### PR TITLE
Fix kill for sessions

### PR DESCRIPTION
**Pull request by rkervella**

### CODE REVIEW

**Comment by rkervella** [comment]
Don't merge yet, there's a bug in the client code too, the CLI hangs.

**Comment by maxlandon** [comment]
Taking care of the bug.

**Comment by rkervella** [comment]
Looks like it's fixed in #1353 . Looks like a deadlock somewhere, but I can't figure out where, even by diffing. If you find it @maxlandon that'd be great, otherwise this will have to wait for a review of #1353 .

**Comment by maxlandon** [comment]
Okay will also do some cross-checks

**Comment by maxlandon** [comment]
Note: merged in #1359 also.

**Pull request merged**
