### PR TITLE
Display More Process Information (`sessions` and `beacons` commands)

### PR DESCRIPTION
**Pull request by RafBishopFox**
This PR should fully address #489. We have been building pieces of that issue in (through `getprivs`). This PR exposes the information requested in that issue (process name, ID, integrity) in one place (the `beacons` and `sessions` commands). Integrity information is only updated when `getprivs` is run.

This is what it looks like:
```
sliver > beacons

 ID         Name            Tasks   Transport   Remote Address       Hostname          Username   Process (PID)                Integrity   Operating System   Locale   Last Check-In                            Next Check-In                         
========== =============== ======= =========== ==================== ================= ========== ============================ =========== ================== ======== ======================================== =======================================
 6ca66a58   MATURE_SNORER   7/7     mtls        10.11.12.132:54099   DESKTOP-R0AA4IE   User       C:\Progs\beacon.exe (8856)   Medium      windows/amd64      en-US    Wed Jan  3 09:53:06 UTC 2024 (12s ago)   Wed Jan  3 09:53:28 UTC 2024 (in 10s)
```

```
sliver > sessions

 ID         Name                  Transport   Remote Address       Hostname          Username   Process (PID)                Integrity   Operating System   Locale   Last Message                               Health  
========== ===================== =========== ==================== ================= ========== ============================ =========== ================== ======== ========================================== =========
 6094227c   IMAGINATIVE_STATION   mtls        10.11.12.132:54098   DESKTOP-R0AA4IE   User       C:\Progs\sliver.exe (6884)   Medium      windows/amd64      en-US    Wed Jan  3 08:04:07 UTC 2024 (1m6s ago)    [ALIVE]
```

Leaving this PR as a draft for now because it would cause issues with #1537. Once that is merged in, I will make the necessary changes to this one so that it can be merged in.

### CODE REVIEW

**Comment by rkervella** [comment]
@RafBishopFox maybe we could filter this out depending on the target GOOS? Process integrity level doesn't mean anything outside of Windows.

**Comment by RafBishopFox** [comment]
@rkervella Sure :slightly_smiling_face: I modified the code slightly to look through the list of sessions or beacons and if there is a Windows one, then the integrity column will be populated. Otherwise, it will be omitted:

Here is an example with sessions. First, we only have a Linux session:
```
sliver > sessions                                                                                                                                                                                                                                                                                       
                                                                           
 ID         Name             Transport   Remote Address      Hostname   Username   Process (PID)        Operating System   Locale   Last Message                               Health  
========== ================ =========== =================== ========== ========== ==================== ================== ======== ========================================== =========
 326206b7   FOLLOWING_RAIN   mtls        10.11.12.13:43592   dev        user       /tmp/sliver (9251)   linux/amd64        en-US    Wed Jan  3 10:49:13 UTC 2024 (1m41s ago)   [ALIVE]
```

Then a Windows session comes to play and `getprivs` is run:
```
sliver > sessions

 ID         Name                  Transport   Remote Address       Hostname          Username   Process (PID)                Integrity   Operating System   Locale   Last Message                             Health  
========== ===================== =========== ==================== ================= ========== ============================ =========== ================== ======== ======================================== =========
 2d0f3089   IMAGINATIVE_STATION   mtls        10.11.12.132:54392   DESKTOP-R0AA4IE   User       C:\Tools\sliver.exe (9524)   Medium      windows/amd64      en-US    Wed Jan  3 10:51:22 UTC 2024 (6s ago)    [ALIVE] 
 326206b7   FOLLOWING_RAIN        mtls        10.11.12.13:43592    dev               user       /tmp/sliver (9251)           -           linux/amd64        en-US    Wed Jan  3 10:51:13 UTC 2024 (15s ago)   [ALIVE]
```

I have not pushed these changes because I am not sure what we want to do in the case of filters. Because filters are applied after the rows are built, I would either have to reconstruct the rows if the final list does not include integrity or apply the filters while building the rows. I am thinking the second option would be easiest, but I was wondering if it is worth doing at all. Without doing anything, the integrity column will be in the filtered output even if there are no beacons / sessions that have integrity info. What are your thoughts? :slightly_smiling_face:

**Comment by rkervella** [comment]
> Because filters are applied after the rows are built, I would either have to reconstruct the rows if the final list does not include integrity or apply the filters while building the rows. I am thinking the second option would be easiest, but I was wondering if it is worth doing at all. Without doing anything, the integrity column will be in the filtered output even if there are no beacons / sessions that have integrity info. What are your thoughts?

Might not be worth doing if they're filtered out anyway.

**Comment by rkervella** [comment]
Some conflicts to be resolved, probably just the `SliverClientConsole` to be renamed to `SliverClient`.

**Comment by RafBishopFox** [comment]
Yup. Now that #1537 has been merged, I will fix this PR and submit it :slightly_smiling_face:

**Review by rkervella — APPROVED** [review]

**Pull request merged**
