### PR TITLE
Add kerberos support for SSH client

### LINKED ISSUE #719: Add kerberos support to embedded SSH client
Add support for kerberos authentication in the implant's ssh client.

### PR DESCRIPTION
**Pull request by rkervella**
Add kerberos authentication support for the embeded SSH client.

Closes #719.

### CODE REVIEW

**Comment by rkervella** [comment]
Hm looks like garble doesn't like these: https://github.com/jcmturner/gokrb5/blob/master/gssapi/MICToken.go#L44-L52

**Comment by rkervella** [comment]
@moloch-- any chance you could update garble to the upstream versions? I can't reproduce locally with an up to date garble build.

**Comment by moloch--** [comment]
Can do.

**Comment by rkervella** [comment]
Well using upstream garble directly seems to work fine, so yeah, when you find some time, if you could update it on your repo that'd be nice :)

**Review by its0x08 — DISMISSED** [review]

**Review by moloch-- — APPROVED** [review]

**Pull request merged**
